# Generated by Django 5.0.1 on 2024-10-30 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='department',
            new_name='department_id',
        ),
    ]
