# Generated by Django 5.1.3 on 2024-11-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseData', '0003_emailverification_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
