# Generated by Django 5.1.3 on 2024-12-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseData', '0004_subject_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeClassSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('free_slots', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseData.class')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseData.department')),
            ],
        ),
    ]
