# Generated by Django 5.1.3 on 2024-12-07 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseData', '0005_freeclassslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeclassslot',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_slots', to='databaseData.class'),
        ),
    ]
