# Generated by Django 5.1.3 on 2024-12-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseData', '0006_alter_freeclassslot_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='freeclassslot',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
