# Generated by Django 5.0.1 on 2024-12-21 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseData', '0007_freeclassslot_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(max_length=10)),
                ('slot', models.CharField(max_length=10)),
                ('semester', models.CharField(max_length=100)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseData.class')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseData.department')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseData.subject')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseData.teacher')),
            ],
        ),
    ]
