# Generated by Django 5.0.1 on 2024-12-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseData', '0008_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='class_department',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheduler',
            name='teacher_department',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
