# Generated by Django 5.0.1 on 2024-12-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseData', '0009_scheduler_class_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='class_department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='teacher_department',
            field=models.CharField(max_length=100),
        ),
    ]
