# Generated by Django 5.1.3 on 2025-01-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseData', '0011_class_given_to_class_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='given_to',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='requested_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
